### ISSUE TITLE
IntelliJ Gradle Testing Support

### ISSUE THREAD

**Issue by gchallen** [kotest/kotest-intellij-plugin#96]
kotest version 4.2.3. Latest version of IntelliJ IDEA CE.

I just recently updated to kotest from kotlintest. In the past, IntelliJ was able to at least identify entire kotlintest `StringSpec` blocks as tests. You could then use `f:` focusing to pick out individual tests to run, even if (IIRC) IntelliJ couldn't identify individual tests within the spec.

Since the upgrade to `kotest` there is no option to run tests. I have tried the `kotest` plugin, but it doesn't seem to honor my settings to run tests with Gradle, which I'd like to continue doing so that I don't need to duplicate test configurations in two places.

Is this the expected behavior—or a bug with the `kotest` IntelliJ plugin, or something wonky about my environment? Unfortunately this represents a fairly serious regression for our use case, since our project has a large number of tests and the entire suite runs quite slowly.

**Comment by gchallen** [comment]
Here's an example: https://github.com/gchallen/kotest-gradle-repo. Note that this is using kotlintest, not kotest. But this is the way that things used to work.

When I open this in IntelliJ here's what I see:

![image](https://user-images.githubusercontent.com/445443/94189182-09a7b700-fe70-11ea-9aa9-2625d7f9f777.png)

And, when I click on the run icon, it runs the test using Gradle:

![image](https://user-images.githubusercontent.com/445443/94189215-15937900-fe70-11ea-8e14-db17f83ee5eb.png)

Note that this is probably because I have some global setting that is configured to run tests with Gradle, rather than with IntelliJ.

I can confirm that this is still broken using the latest version of the kotest plugin, but perhaps you have not yet pushed this fix. Let me know how I can help. This is becoming a big usability problem at this point, after making a fairly large investment in porting kotlintest over to kotest...

**Comment by sksamuel** [comment]
Which version of intellij @gchallen

**Comment by gchallen** [comment]
Latest CE: 2020.2.

**Comment by gchallen** [comment]
Any update on this issue? Again, this causes severe usability issues with `kotest`. I can't be the only person experiencing this.

**Comment by sksamuel** [comment]
I think this is good now. I have the plugin able to detect the gradle/intellij settings.

![image](https://user-images.githubusercontent.com/743706/95028508-48a2ed00-0666-11eb-8840-5e9d6d7c8a52.png)

It would be very useful if you could test this. Attached is a build for 2020.2. You would need to uninstall the version you have, and add this manually via the install from disk option in plugin settings.

[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.2.zip](https://github.com/kotest/kotest-intellij-plugin/files/5324529/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.2.zip)

**Comment by sksamuel** [comment]
How are you getting on with the new build @gchallen ?

**Comment by gchallen** [comment]
Thanks! Haven't tested yet... Will soon.

**Comment by gchallen** [comment]
Looks great! Thanks for fixing this.

**Comment by sksamuel** [comment]
Cool

**Comment by mriehl** [comment]
What's the status on this? I'm using the kotest intellij plugin `1.1.24-IC-2020.3` and I cannot get idea to run the tests with gradle. The "run tests using" option is set to gradle, and I've tried deleting the test configurations, but no luck so far.
